name: CI

on:
  workflow_dispatch:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

env:
  SONAR_TOKEN: sqp_5c4a5f5f512fa10b024ac64637ed817567d7cc65
  SONAR_HOST_URL: http://104.248.145.17:9000
  SONAR_PROJECT_KEY: nextjs-fullstack

jobs:
  sonarqube:
    name: SonarQube Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ env.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ env.SONAR_HOST_URL }}
        with:
          args: >
            -Dsonar.projectKey=${{ env.SONAR_PROJECT_KEY }}
            -Dsonar.sources=app
